### PR TITLE
Features/secrets config file

### PR DESCRIPTION
**Pull request by driskell**
Hi emsearcy,

I did a bit of housecleaning and added the secrets file option.
Also updated and improved README and converted to markdown format.

Let me know if you prefer to just pull the secret file changes and I will create a branch for you to pull. But if you don't mind the tidying, readme and version stuff I've done, here it all is!

I've tested it for a couple hours on my server and is all running fine. I will test it further for another week or two. Feel free to give it a test too before you accept anything.

Regards,

Jason

### CODE REVIEW

**Comment by driskell** [comment]
Assume the project is dead. I will keep my fork live if anyone needs it.

**Comment by emsearcy** [comment]
Actually, I just never noticed the issue!

**Comment by driskell** [comment]
Haha sorry :) - if you are interested though I can reopen the PR. Just shout!

**Comment by driskell** [comment]
Do you want me to reopen to review?

I also have a PR in my fork from someone else regarding a crash. Can reproduce by telnet manually and just hit enter. Causes default if verbose logging enabled.

**Comment by emsearcy** [comment]
Thank you driskell for these features and fixes!  I think the spec file should say 0.0.2-1 in the changelog instead of 0.0.1-3, though.

**Comment by emsearcy** [comment]
I'll just go ahead and merge this.  Maybe we can update the version again as part of the segfault review and fix the changelog then.  I guess we need to figure out how to do versioning... maybe secrets file should be 0.2.1-1 and the segfault fix should be 0.2.2-1 (leave major number reserved for some future purpose, use minor number for feature changes, micro number for bug fixes, -rev for packaging changes?)

**Pull request merged**
